### ISSUE TITLE
missing ubuntu package 

### ISSUE THREAD

**Issue by caifti** [indigo-dc/cloud-info-provider-deep#11]
# Short Description of the issue

On Ubuntu the package cloud-info-provider-deep is missing, making impossible the installation of cloud-info-provider-deep-openstack 

## Environment

- Operating System:
- python version:
- OpenStack version:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by orviz** [comment]
Thanks @caifti for the heads-up, working on it
